services:
  scheduler:
    build:
      context: .
      dockerfile: docker/stage/Dockerfile
    container_name: stack-scheduler-stage
    volumes:
      - .:/src       # Mount your source code
      - ./data:/data # SQLite persistence
      - /var/run/docker.sock:/var/run/docker.sock
      - go-cache:/go # faster builds
    ports:
      - "8044:8044"
    working_dir: /src
    command: ["air", "-c", "/src/.air.toml"]

    environment:
      APP_ENV: dev
      APP_PORT: 8044
      DB_PATH: /data/app.db
      AIR_POLL: true
      JWT_SECRET: stage-secret-change-me

volumes:
  go-cache:
